### ISSUE TITLE
ticketutil doesn't work with RH bugzilla

### ISSUE THREAD

**Issue by vashirov** [dmranck/ticketutil#28]
```
ERROR:root:Error authenticating to https://bugzilla.redhat.com/rest/login.
ERROR:root:404 Client Error: Not Found for url: https://bugzilla.redhat.com/rest/login?login=username&password=password
Traceback (most recent call last):
  File "create_jira_ticket.py", line 12, in <module>
    ticket_id=1447393)
  File "/home/vashirov/.local/lib/python2.7/site-packages/ticketutil/bugzilla.py", line 28, in __init__
    super(BugzillaTicket, self).__init__(project, ticket_id)
  File "/home/vashirov/.local/lib/python2.7/site-packages/ticketutil/ticket.py", line 43, in __init__
    raise TicketException("Error authenticating to {0}.".format(self.auth_url))
ticketutil.ticket.TicketException: Error authenticating to https://bugzilla.redhat.com/rest/login.
```

**Comment by dmranck** [comment]
This issue is a result of Bugzilla 4 not supporting the REST API. RH Bugzilla is in the process of migrating to Bugzilla version 5, which will add REST API support. We will make sure ticketutil works with RH Bugzilla once the migration is complete.
